<?php

/**
 * Autogenerated file for problem PowerOfFour
 */

namespace LeetCode\Problems\PowerOfFour;

class PowerOfFour
{
    /**
     * @param int $n
     * @return Boolean
     */
    function isPowerOfFour($n)
    {
        if ($n <= 0) {
            return false;
        }
        if ($n == 1) {
            return true;
        }
        if ($n % 4 != 0) {
            return false;
        }
        return $this->isPowerOfFour($n / 4);
    }
}
