<?php

/**
 * Autogenerated file for problem ContainsDuplicate
 */

namespace LeetCode\Problems\ContainsDuplicate;

class ContainsDuplicate
{
    /**
     * @param Integer[] $nums
     * @return Boolean
     */
    function containsDuplicate($nums) {
        $originalLength = count($nums);
        $uniqueLength = count(array_unique($nums));
        return $originalLength == $uniqueLength ? false : true;
    }
}
