<?php

/**
 * Autogenerated file for problem ReverseBits
 */

namespace LeetCode\Problems\ReverseBits;

class ReverseBits
{
    /**
     * @param Integer $n
     * @return Integer
     */
    public function reverseBits($n)
    {
        $res = 0;
        for ($i = 0; $i < 32; $i++) {
            $res <<= 1;
            $res += $n & 1;
            $n >>= 1;
        }
        return $res >> 0;
    }
}
