<?php

/**
 * Autogenerated file for problem DesignHashset
 */

namespace LeetCode\Problems\DesignHashset;

class DesignHashset
{
    protected $hashSet;

    /**
     */
    function __construct() {
        $this->hashSet = [];
    }
    
    /**
     * @param Integer $key
     * @return NULL
     */
    function add($key) {
        $this->hashSet[$key] = $key;
    }
    
    /**
     * @param Integer $key
     * @return NULL
     */
    function remove($key) {
        if (array_key_exists($key, $this->hashSet)) {
            unset($this->hashSet[$key]);
            return TRUE;
        }
        return FALSE;
    }
    
    /**
     * @param Integer $key
     * @return Boolean
     */
    function contains($key) {
        return isset($this->hashSet[$key]);
    }
}
