<?php

/**
 * Autogenerated file for problem DesignHashset
 */

namespace LeetCode\Problems\DesignHashset;

class DesignHashset
{
    protected $hashSet;

    /**
     */
    public function __construct()
    {
        $this->hashSet = [];
    }

    /**
     * @param Integer $key
     * @return NULL
     */
    public function add($key)
    {
        $this->hashSet[$key] = $key;
    }

    /**
     * @param Integer $key
     * @return NULL
     */
    public function remove($key)
    {
        if (array_key_exists($key, $this->hashSet)) {
            unset($this->hashSet[$key]);
            return true;
        }
        return false;
    }

    /**
     * @param Integer $key
     * @return Boolean
     */
    public function contains($key)
    {
        return isset($this->hashSet[$key]);
    }
}
