<?php

/**
 * Autogenerated file for problem ValidAnagram
 */

namespace LeetCode\Problems\ValidAnagram;

class ValidAnagram
{
    /**
     * @param String $s
     * @param String $t
     * @return Boolean
     */
    public function isAnagram($s, $t)
    {
        $length = strlen($t);
        if ($length != strlen($s)) {
            return false;
        }
        $anagramString = str_split($s);
        $flag = false;
        $i = 0;
        while ($i < $length) {
            $key = array_search($t[$i], $anagramString);
            if ($key !== false) {
                $anagramString[$key] = 99999;
                $flag = true;
            } else {
                $flag = false;
                break;
            }
            $i++;
        }
        return $flag;
    }
}
