<?php

/**
 * Autogenerated file for problem RangeSumQuery
 */

namespace LeetCode\Problems\RangeSumQuery;

class RangeSumQuery
{
    private $nums;

    /**
     * @param int[] $nums
     */
    public function __construct($nums)
    {
        $this->nums = $nums;
    }

    /**
     * @param int $left
     * @param int $right
     * @return int
     */
    public function sumRange($left, $right)
    {
        $sum = 0;
        for ($i = $left; $i <= $right; $i++) {
            $sum += $this->nums[$i];
        }
        return $sum;
    }
}

// [[[-2, 0, 3, -5, 2, -1]], [0, 2], [2, 5], [0, 5]];
