<?php

/**
 * Autogenerated file for problem GuessNumberHigherLower
 */

namespace LeetCode\Problems\GuessNumberHigherLower;

class GuessNumberHigherLower
{
    protected $pick = 6;

    /**
     * @param  Integer  $n
     * @return Integer
     */
    public function guessNumber($n)
    {
        $result = $this->guess($n);
        $start = 0;
        $end = $n;
        while ($result != 0) {
            $n = round(($start + $end) / 2);
            $result = $this->guess($n);
            if ($result == 1) {
                $start = $n;
            } elseif ($result == -1) {
                $end = $n;
            }
        }
        return $n;
    }

    public function guess($n)
    {
        return $this->pick <=> $n;
    }
}
