<?php

/**
 * Autogenerated file for problem IsPowerOfThree
 */

namespace LeetCode\Problems\IsPowerOfThree;

class IsPowerOfThree
{
    /**
     * @param int $n
     * @return Boolean
     */
    function isPowerOfThree($n) {
        if ($n <= 0) {
            return false;
        }
        if ($n == 1) {
            return true;
        }
        if ($n % 3 != 0) {
            return false;
        }
        return $this->isPowerOfThree($n / 3);
    }
}
