<?php

/**
 * Autogenerated file for problem CountPrefixesGivenString
 */

namespace LeetCode\Problems\CountPrefixesGivenString;

class CountPrefixesGivenString
{
    /**
     * @param String[] $words
     * @param String $s
     * @return Integer
     */
    public function countPrefixes($words, $s)
    {
        $count = 0;
        foreach ($words as $value) {
            if (stripos($s, $value) === 0) {
                $count++;
            }
        }
        return $count;
    }
}
