<?php

/**
 * Autogenerated file for problem FizzBuzz
 */

namespace LeetCode\Problems\FizzBuzz;

class FizzBuzz
{
    /**
     * @param int $n
     * @return String[]
     */
    public function fizzBuzz($n)
    {
        $op = [];
        $both = false;
        for ($i = 1; $i <= $n; $i++) {
            $op[$i - 1] = (string)$i;
            if ($i % 3 === 0) {
                $op[$i - 1] = "Fizz";
                $both = true;
            }
            if ($i % 5 === 0) {
                $op[$i - 1] = $both === true ? "FizzBuzz" : "Buzz";
            }
            $both = false;
        }
        return $op;
    }
}
