<?php

/**
 * Autogenerated file for problem PalindromeLinkedList
 */

namespace LeetCode\Problems\PalindromeLinkedList;

class PalindromeLinkedList
{
    /**
     * @param ListNode $head
     * @return Boolean
     */
    public function isPalindrome($head)
    {
        if (!$head) {
            return false;
        }
        $numbers = [];
        $length = 0;
        while ($head != null) {
            $numbers[] = $head->val;
            $length++;
            $head = $head->next;
        }
        $mid = $length / 2;
        $i = 0;
        $j = $length - 1;
        $flag = true;
        while ($i < $mid && $j >= $mid) {
            if ($numbers[$i] != $numbers[$j]) {
                $flag = false;
                break;
            }
            $i++;
            $j--;
        }
        return $flag;
    }
}
