<?php

/**
 * Autogenerated file for problem DeleteColumnsMakeSorted
 */

namespace LeetCode\Problems\DeleteColumnsMakeSorted;

class DeleteColumnsMakeSorted
{
    /**
     * @param String[] $strs
     * @return Integer
     */
    function minDeletionSize($strs) {
        $n = strlen($strs[0]);
        $total = 0;
        $k = 0;
        for ($i=0; $i<$n; $i++) {
            $ord = 0;
            foreach($strs as $key => $val) {
                if (isset($val[$k]) && $ord <= ord($val[$k])) {
                    $ord = ord($val[$k]);
                } else {
                    if (isset($val[$k])) {
                        $total++;
                        break;
                    }
                }
            }
            $k++;
        }
        return $total;
    }
}
