<?php

/**
 * Autogenerated file for problem LongestCommonPrefix
 */

namespace LeetCode\Problems\LongestCommonPrefix;

class LongestCommonPrefix
{
    /**
     * @param String[] $strs
     * @return String
     */
    function longestCommonPrefix($strs) {
        if (count($strs) === 1) {
            return $strs[0];
        }
        $prefix = '';
        $result = '';
        $isPrefixCommon = false;
        for ($i=0; $i<strlen($strs[0]); $i++) {
            $prefix .= $strs[0][$i];
            foreach ($strs as $value) {
                if (strpos($value, $prefix) === 0) {
                    $isPrefixCommon = true;
                } else {
                    $isPrefixCommon = false;
                    break;
                }
            }
            if ($isPrefixCommon) {
                $result = $prefix;
            }
            $isPrefixCommon = false;
        }
        return $result;
    }
}
