<?php

/**
 * Autogenerated file for problem ClimbingStairs
 */

namespace LeetCode\Problems\ClimbingStairs;

class ClimbingStairs
{
    /**
     * @param Integer $n
     * @return Integer
     */
    function climbStairs($n)
    {
        if ($n == 1)
            return 1;
        else if ($n == 2)
            return 2;
        
        $ways = [1,1,2];
        for($i=3; $i<= $n; $i++) {
            $ways[$i] = $ways[$i-1] + $ways[$i-2];
        }
        return $ways[$n];
    }
}
