<?php

/**
 * Autogenerated file for problem AddBinary
 */

namespace LeetCode\Problems\AddBinary;

class AddBinary
{
    /**
     * @param String $a
     * @param String $b
     * @return String
     */
    public function addBinary($a, $b)
    {
        $c = 0;
        $res = [];
        $as = strlen($a);
        $bs = strlen($b);
        while ($as > 0 || $bs > 0) {
            $bs--;
            $as--;
            $an = $as >= 0 ? $a[$as] : 0;
            $bn = $bs >= 0 ? $b[$bs] : 0;
            $s = intval($an) + intval($bn) + $c;
            if ($s == 2) {
                $s = 0;
                $c = 1;
            } elseif ($s == 3) {
                $s = 1;
                $c = 1;
            } else {
                $c = 0;
            }
            array_unshift($res, $s);
        }
        if ($c == 1) {
            array_unshift($res, $c);
        }
        return implode($res);
    }
}
