<?php

/**
 * Autogenerated file for problem StringContainsAllBinaryCodes
 */

namespace LeetCode\Problems\StringContainsAllBinaryCodes;

class StringContainsAllBinaryCodes
{
    /**
     * @param String $s
     * @param Integer $k
     * @return Boolean
     */
    public function hasAllCodes($s, $k)
    {
        $need = 1 << $k;
        $got = [];

        for ($i = $k; $i <= strlen($s); $i++) {
            $a = substr($s, $i - $k, $i);
            if (!in_array($a, $got)) {
                $got[] = $a;
                $need--;
                if ($need == 0) {
                    return true;
                }
            }
        }
        return false;
    }
}
