<?php

/**
 * Autogenerated file for problem UglyNumber
 */

namespace LeetCode\Problems\UglyNumber;

class UglyNumber
{
    /**
     * @param Integer $n
     * @return Boolean
     */
    public function isUgly($n)
    {
        if ($n < 0) {
            return false;
        }
        if ($n == 1) {
            return true;
        }
        while ($n > 1) {
            if ($n % 2 == 0) {
                $n = $n / 2;
            } elseif ($n % 3 == 0) {
                $n = $n / 3;
            } elseif ($n % 5 == 0) {
                $n = $n / 5;
            } else {
                return false;
            }
        }
        return $n == 1;
    }
}
