<?php

/**
 * Autogenerated file for problem DesignHashMap
 */

namespace LeetCode\Problems\DesignHashMap;

class DesignHashMap
{
    protected $stack;
    
    /**
     */
    function __construct() {
        $this->stack = [];
    }
    
    /**
     * @param Integer $key
     * @param Integer $value
     * @return NULL
     */
    function put($key, $value) {
        $this->stack[$key] = $value;
    }
    
    /**
     * @param Integer $key
     * @return Integer
     */
    function get($key) {
        return $this->stack[$key] ?? -1;
    }
    
    /**
     * @param Integer $key
     * @return NULL
     */
    function remove($key) {
        unset($this->stack[$key]);
    }
}
