<?php

/**
 * Autogenerated file for problem ValidParentheses
 */

namespace LeetCode\Problems\ValidParentheses;

class ValidParentheses
{
    /**
     * @param String $s
     * @return Boolean
     */
    public function isValid($s)
    {
        $length = strlen($s);
        if ($length % 2 !== 0) {
            return false;
        }
        $parentheses = [
            "(" => ")",
            "[" => "]",
            "{" => "}",
        ];
        $stack = array();
        for($i = 0; $i < strlen($s); $i++) {
            if (isset($parentheses[$s[$i]])) {
                array_push($stack, $s[$i]);
            } else {
                $parenthesis = array_pop($stack);
                if ($s[$i] != ($parentheses[$parenthesis] ?? '')) {
                    return false;
                }
            }
        }

        return empty($stack);
    }
}
