<?php

/**
 * Autogenerated file for problem ImplementStrStr
 */

namespace LeetCode\Problems\ImplementStrStr;

class ImplementStrStr
{
    /**
     * @param String $haystack
     * @param String $needle
     * @return Integer
     */
    public function strStr($haystack, $needle)
    {
        if (empty($needle)) {
            return 0;
        }
        $flag = stripos($haystack, $needle);
        return $flag !== false ? $flag : -1;
    }
}
