<?php

/**
 * Autogenerated file for problem PalindromicSubstrings
 */

namespace LeetCode\Problems\PalindromicSubstrings;

class PalindromicSubstrings
{
    protected $count = 0;
    /**
     * @param String $s
     * @return Integer
     */
    public function countSubstrings($s)
    {
        $length = strlen($s);
        for ($i = 0; $i < $length; $i++) {
            $low = $i;
            $high = $i;
            while ($high < $length && $low >= 0) {
                if ($s[$low] == $s[$high]) {
                    $this->count++;
                }
                $low--;
                $high++;
            }
        }
        return $this->count;
    }
}
