<?php

/**
 * Autogenerated test case file for problem IntersectionTwoArraysIITest
 */

use LeetCode\Problems\IntersectionTwoArraysII\IntersectionTwoArraysII;
use PHPUnit\Framework\TestCase;
final class IntersectionTwoArraysIITest extends TestCase
{
	public function testIntersectionTwoArraysIITestExample1()
	{
	}
}
