<?php

/**
 * Autogenerated file for problem WordPattern
 */

namespace LeetCode\Problems\WordPattern;

class WordPattern
{
    /**
     * @param String $pattern
     * @param String $s
     * @return Boolean
     */
    function wordPattern($pattern, $s) {
        if (empty($pattern)) return false;
        $parts = explode(' ', $s);
        $p_len = strlen($pattern);
        if ($p_len !== count($parts)) return false;
        $map = []; $r_map = [];
        $flag = false;
        for($i=0; $i<$p_len;$i++) {
            if (!isset($map[$pattern[$i]])) {
                $map[$pattern[$i]] = $parts[$i];
            }
            if ($map[$pattern[$i]] == $parts[$i]) {
                $flag = true;
            } else {
                $flag = false;
                break;
            }
        }
        return $flag;
    }
}
