<?php

/**
 * Autogenerated file for problem ThirdMaximumNumber
 */

namespace LeetCode\Problems\ThirdMaximumNumber;

class ThirdMaximumNumber
{
    /**
     * @param Integer[] $nums
     * @return Integer
     */
    public function thirdMax($nums)
    {
        $unique = array_unique($nums);
        $position = count($unique) >= 3 ? 3 : 1;
        sort($unique);
        return $unique[count($unique) - $position];
    }
}
