<?php

/**
 * Autogenerated file for problem RemoveDuplicatesSortedArray
 */

namespace LeetCode\Problems\RemoveDuplicatesSortedArray;

class RemoveDuplicatesSortedArray
{
    /**
     * @param Integer[] $nums
     * @return Integer
     */
    function removeDuplicates(&$nums) {
        $totalCount = 0;
        $count = count($nums);
        foreach ($nums as $key => $value) {
            if ($key != ($count-1) && $value == $nums[$key + 1]) {
                $nums[] = $nums[$key + 1];
                unset($nums[$key + 1]);
            } else {
                $totalCount++;
            }
        }
        return $totalCount;
    }
}
