<?php

/**
 * Autogenerated file for problem ValidPalindrome
 */

namespace LeetCode\Problems\ValidPalindrome;

class ValidPalindrome
{
    /**
     * @param String $s
     * @return Boolean
     */
    function isPalindrome($s) {
        if (!$s)
            return true;
        $s = strtolower($s);
        if (strrev($s) == $s) {
            return true;
        }
        $s = preg_replace('/(\W)*(_)*/', '', $s);
        if (strrev($s) == $s) {
            return true;
        }
        return false;
    }
}
