<?php

/**
 * Autogenerated file for problem SingleNumber
 */

namespace LeetCode\Problems\SingleNumber;

class SingleNumber
{
    /**
     * @param Integer[] $nums
     * @return Integer
     */
    public function singleNumber($nums)
    {
        $max = 0;
        foreach (array_count_values($nums) as $key => $value) {
            if ($value == 1) {
                $max = $key;
                break;
            }
        }
        return $max;
    }

    public function singleNumberA1($nums)
    {
        $length = count($nums);
        $max = 0;
        for ($i = 0;$i < $length;$i++) {
            $max = $max ^ $nums[$i];
        }
        return $max;
    }
}
