<?php

/**
 * Autogenerated file for problem MajorityElement
 */

namespace LeetCode\Problems\MajorityElement;

class MajorityElement
{
    /**
     * @param Integer[] $nums
     * @return Integer
     */
    public function majorityElement($nums)
    {
        $length = count($nums);
        $total = $max = 0;
        $parsed = [];
        for ($i = 0;$i < $length;$i++) {
            if (in_array($nums[$i], $parsed)) {
                continue;
            }
            for ($j = 0; $j < $length; $j++) {
                if ($nums[$i] === $nums[$j]) {
                    $max++;
                }
            }
            $total = $max > $length / 2 ? $i : $total;
            $parsed[]  = $nums[$i];
            $max = 0;
        }
        return $nums[$total];
    }
}
