<?php

/**
 * Autogenerated file for problem LengthofLastWord
 */

namespace LeetCode\Problems\LengthofLastWord;

class LengthofLastWord
{
    /**
     * @param String $s
     * @return Integer
     */
    function lengthOfLastWord($s)
    {
        $s = explode(" ", trim($s));
        return strlen($s[count($s)-1]);
    }
}
