<?php

/**
 * Autogenerated file for problem PathMinimumEffort
 */

namespace LeetCode\Problems\PathMinimumEffort;

class PathMinimumEffort
{
    /**
     * @param Integer[][] $heights
     * @return Integer
     */
    function minimumEffortPath($heights) {
        $n = count($heights);
        $m = count($heights[0]);
        $dist = [];
        for ($i = 0; $i < $n; $i++) {
            $dist[] = array_fill(0, $m, PHP_INT_MAX);
        }
        $minHeap = new SplMinHeap();
        $minHeap->insert([0, 0, 0]);
        $dir = [0, 1, 0, -1, 0];
        print_r($dist);die;
    }
}
