<?php

/**
 * Autogenerated file for problem OnesandZeroes
 */

namespace LeetCode\Problems\OnesandZeroes;

class OnesandZeroes
{
    /**
     * @param String[] $strs
     * @param Integer $m
     * @param Integer $n
     * @return Integer
     */
    function findMaxForm($strs, $m, $n) {
        $count=0;
        foreach($strs as $key => $value) {
            $listCount = array_count_values(str_split($value));
            $zeroCount = $listCount[0] ?? 0;
            $oneCount = $listCount[1] ?? 0;
            if ($zeroCount <= $m && $oneCount <= $n) {
                $count++;
            }
        }
        return $count;
    }
}
