<?php

/**
 * Autogenerated file for problem BalancedBinaryTree
 */

namespace LeetCode\Problems\BalancedBinaryTree;

class BalancedBinaryTree
{
    /**
     * @param TreeNode $root
     * @return Boolean
     */
    public function isBalanced($root)
    {
        if (is_null($root)) {
            return true;
        }
        $left = $this->getHeight($root->left);
        $right = $this->getHeight($root->right);
        return abs($left - $right) < 2;
    }

    public function getHeight($a)
    {
        if (is_null($a)) {
            return 0;
        }
        if (is_null($a->left) && is_null($a->right)) {
            return 1;
        }
        return max($this->getHeight($a->left), $this->getHeight($a->right)) + 1;
    }
}
