<?php

/**
 * Autogenerated file for problem DivideTwoIntegers
 */

namespace LeetCode\Problems\DivideTwoIntegers;

class DivideTwoIntegers
{
    /**
     * @param Integer $dividend
     * @param Integer $divisor
     * @return Integer
     */
    public function divide($dividend, $divisor)
    {
        $isDividendNegate = $dividend < 0;
        $isDivisorNegate = $divisor < 0;
        $remainder = abs($dividend);
        $count = 0;
        while ($remainder > 0) {
            $remainder -= abs($divisor);
            $count++;
        }
        if ($remainder != 0) {
            $count--;
        }
        if ($isDividendNegate && $isDivisorNegate) {
            $count *= 1;
        } elseif ($isDividendNegate || $isDivisorNegate) {
            $count *= -1;
        }
        return ($count);
    }
}
