<?php

/**
 * Autogenerated file for problem MaximumDepthBinaryTree
 */

namespace LeetCode\Problems\MaximumDepthBinaryTree;

class MaximumDepthBinaryTree
{
    protected $result =  [];
    
    /**
     * @param TreeNode $root
     * @return Integer
     */
    function maxDepth($root) {
        $this->parsePath($root, 0);
        if (count($this->result) == 0) {
            return 0;
        } else {
            return max($this->result);
        }
    }
    
    function parsePath($root, $path) {
        if (is_null($root)) {
            return;
        }
        $path += 1;
        $this->parsePath($root->left, $path);
        $this->parsePath($root->right, $path);
        if ($root->left == null && $root->right == null) {
            $this->result[] = $path;
        }
    }
}
