<?php

/**
 * Autogenerated file for problem MoveZeroes
 */

namespace LeetCode\Problems\MoveZeroes;

class MoveZeroes
{
    /**
     * @param Integer[] $nums
     * @return NULL
     */
    public function moveZeroes(&$nums)
    {
        $size = count($nums);
        $nonZero = 0;
        for ($i = 0;$i < $size;$i++) {
            if ($nums[$i] != 0) {
                $nums[$nonZero++] = $nums[$i];
            }
        }
        for ($i = $nonZero;$i < $size;$i++) {
            $nums[$i] = 0;
        }
        return $nums;
    }
}
