<?php

/**
 * Autogenerated file for problem TransposeMatrix
 */

namespace LeetCode\Problems\TransposeMatrix;

class TransposeMatrix
{
    /**
     * @param Integer[][] $matrix
     * @return Integer[][]
     */
    public function transpose($matrix)
    {
        $A = $matrix;
        list($rows, $cols) = [count($A), count($A[0])];
        $transposed = array_fill(0, $cols, array_fill(0, $rows, null));
        for ($i = 0; $i < $rows; $i++) {
            for ($j = 0; $j < $cols; $j++) {
                $transposed[$j][$i] = $A[$i][$j];
            }
        }
        return $transposed;
    }
}
