<?php

/**
 * Autogenerated file for problem ContainerMostWater
 */

namespace LeetCode\Problems\ContainerMostWater;

use SebastianBergmann\CodeCoverage\Report\PHP;

class ContainerMostWater
{
    /**
     * @param Integer[] $height
     * @return Integer
     */
    public function maxArea($height)
    {
        $index = 0;
        $last = count($height) - 1;
        $area = PHP_INT_MIN;
        while ($index < $last) {
            $area = max($area, min($height[$index], $height[$last]) * ($last - $index));
            $height[$index] < $height[$last] ? $index++ : $last--;
        }
        return $area;
    }
}
