<?php

/**
 * Autogenerated file for problem Sqrt
 */

namespace LeetCode\Problems\Sqrt;

class Sqrt
{
    /**
     * @param Integer $x
     * @return Integer
     */
    function mySqrt($x)
    {
        for($i = 0; $i < $x; $i++) {
            $prod = $i*$i;
            if ($prod == $x) {
                return $i;
            } else if ($prod > $x) {
                return $i-1;
            }
        }
    }
}
