<?php

/**
 * Autogenerated file for problem MergeSortedArray
 */

namespace LeetCode\Problems\MergeSortedArray;

class MergeSortedArray
{
    /**
     * @param Integer[] $nums1
     * @param Integer $m
     * @param Integer[] $nums2
     * @param Integer $n
     * @return NULL
     */
    public function merge(&$nums1, $m, $nums2, $n)
    {
        for ($i = $m;$i < ($m + $n);$i++) {
            $nums1[$i] = array_shift($nums2);
        }
        sort($nums1);
    }
}
