<?php

/**
 * Autogenerated file for problem BinaryTreePostorderTraversal
 */

namespace LeetCode\Problems\BinaryTreePostorderTraversal;

class BinaryTreePostorderTraversal
{
    /**
     * @param TreeNode $root
     * @return Integer[]
     */
    public function postorderTraversal($root)
    {
        if (!$root) {
            return [];
        }
        return $this->parseTree($root);
    }

    public function parseTree($node = null)
    {
        $ret = [];
        // Get the Left childs
        if (isset($node->left)) {
            $temp = $this->parseTree($node->left);
            $ret = array_merge($ret, $temp);
        }
        if (isset($node->right)) {
            $temp = $this->parseTree($node->right);
            $ret = array_merge($ret, $temp);
        }
        if (isset($node)) {
            $ret[] = $node->val;
        }
        return $ret;
    }
}
