<?php

/**
 * Autogenerated file for problem SearchInsertPosition
 */

namespace LeetCode\Problems\SearchInsertPosition;

class SearchInsertPosition
{
    /**
     * @param Integer[] $nums
     * @param Integer $target
     * @return Integer
     */
    public function searchInsert($nums, $target)
    {
        $start = 0;
        $end = count($nums) - 1;
        while ($start <= $end) {
            $mid = round(($start + $end) / 2);
            if ($nums[$mid] === $target) {
                return $mid;
            } elseif ($nums[$mid] < $target) {
                $start = $mid + 1;
            } elseif  ($nums[$mid] > $target) {
                $end = $mid - 1;
            }
        }
        return $start;
    }
}
