<?php

/**
 * Autogenerated file for problem RemovePalindromicSubsequences
 */

namespace LeetCode\Problems\RemovePalindromicSubsequences;

class RemovePalindromicSubsequences
{
    /**
     * @param String $s
     * @return Integer
     */
    function removePalindromeSub($s) {
        if(!$s)
            return 0;
        else if($s==strrev($s))
            return 1;
        else
            return 2;
    }
}
