<?php

/**
 * Autogenerated file for problem KidsWithGreatestNumberCandies
 */

namespace LeetCode\Problems\KidsWithGreatestNumberCandies;

class KidsWithGreatestNumberCandies
{
    /**
     * @param array<int> $candies
     * @param int $extraCandies
     * @return array<bool>
     */
    function kidsWithCandies(array $candies, $extraCandies)
    {
        $big = max($candies);
        $result = [];
        $kidsWithCandies = count($candies);
        for ($i = 0; $i < $kidsWithCandies; $i++) {
            $result[] = ($candies[$i] + $extraCandies) >= $big;
        }
        return $result;
    }
}
