<?php

/**
 * Autogenerated file for problem IntersectionTwoLinkedLists
 */

namespace LeetCode\Problems\IntersectionTwoLinkedLists;

class IntersectionTwoLinkedLists
{
    /**
     * @param ListNode $headA
     * @param ListNode $headB
     * @return ListNode
     */
    function getIntersectionNode($headA, $headB) {
        if (!$headA->val || !$headB->val) return null;
        
        $aMapping = [];
        
        while ($headA != null) {
            $aMapping[] = spl_object_id($headA);
            $headA = $headA->next;
        }
        
        while ($headB != null) {
            if (in_array(spl_object_id($headB), $aMapping)) {
                break;
            }
            $headB = $headB->next;
        }
        return $headB;
        
    }
}
