<?php

/**
 * Autogenerated file for problem PowerTwo
 */

namespace LeetCode\Problems\PowerTwo;

class PowerTwo
{
    /**
     * @param Integer $n
     * @return Boolean
     */
    public function isPowerOfTwo($n)
    {
        if ($n == 1 || $n == 2) {
            return true;
        }
        while ($n > 2) {
            $n = $n / 2;
        }
        return $n == 2;
    }
}
