<?php

/**
 * Autogenerated file for problem FirstUniqueCharacterString
 */

namespace LeetCode\Problems\FirstUniqueCharacterString;

class FirstUniqueCharacterString
{
    /**
     * @param String $s
     * @return Integer
     */
    function firstUniqChar($s) {
        $charList = array_count_values(str_split($s));
        $char = '';
        foreach ($charList as $key => $value) {
            if ($value == 1) {
                $char = $key;
                break;
            }
        }
        if (empty($char)) {
            return -1;
        } else {
            return strpos($s, $char);
        }
    }
}
