<?php

/**
 * Autogenerated file for problem BestTimeBuySellStock
 */

namespace LeetCode\Problems\BestTimeBuySellStock;

class BestTimeBuySellStock
{
    /**
     * @param Integer[] $prices
     * @return Integer
     */
    public function maxProfit($prices)
    {
        $min = $prices[0];
        $minIndex = 0;
        $max = $prices[0];
        $profit = 0;
        for ($i = 1; $i < count($prices); $i++) {
            if ($min < $prices[$i]) {
                $min = $min;
            } else {
                $min = $prices[$i];
                $minIndex = $i;
            }
            $max = $max > $prices[$i] && $minIndex < $i ? $max : $prices[$i];
            $profit = $max - $min > $profit ? $max - $min : $profit;
        }
        return $profit;
    }

    /**
     * @param Integer[] $prices
     * @return Integer
     */
    public function maxProfitA1($prices)
    {
        $length = count($prices);
        $min = $prices[0];
        $profit = 0;
        for ($i = 1; $i < $length; $i++) {
            if ($prices[$i] < $min) {
                $min = $prices[$i];
            } elseif ($prices[$i] - $min > $profit) {
                $profit = $prices[$i] - $min;
            }
        }
        return $profit;
    }
}
