<?php

/**
 * Autogenerated file for problem RemoveElement
 */

namespace LeetCode\Problems\RemoveElement;

class RemoveElement
{
    /**
     * @param Integer[] $nums
     * @param Integer $val
     * @return Integer
     */
    function removeElement(&$nums, $val) {
        $totalCount = 0;
        foreach ($nums as $key => $value) {
            if ($value == $val) {
                unset($nums[$key]);
            } else {
                $totalCount++;
            }
        }
        return $totalCount;
    }
}
