<?php

/**
 * Autogenerated file for problem RemoveOutermostParentheses
 */

namespace LeetCode\Problems\RemoveOutermostParentheses;

class RemoveOutermostParentheses
{
    /**
     * @param String $s
     * @return String
     */
    function removeOuterParentheses($s) {
        $length = strlen($s);
        $depth = 1;
        $outerParenthesis = '';
        $start = 0;
        for ($i=1; $i<$length; $i++) {
            if ($s[$i] === '(') {
                $depth++;
            } else if ($s[$i] === ')') {
                $depth--;
            }
            if ($depth == 0) {
                $outerParenthesis .= substr($s, $start+1, $i - $start -1);
                $start = $i + 1;
            }
        }
        return $outerParenthesis;
    }
}
