<?php

/**
 * Autogenerated file for problem MinStack
 */

namespace LeetCode\Problems\MinStack;

class MinStack {
    private $list;
    private $pointer;
    /**
     */
    function __construct() {
        $this->list = [];
        $this->pointer = -1;
    }
    
    /**
     * @param Integer $val
     * @return NULL
     */
    function push($val) {
        $this->pointer=$this->pointer + 1;
        $this->list[$this->pointer] = $val;
    }
    
    /**
     * @return NULL
     */
    function pop() {
        unset($this->list[$this->pointer]);
        $this->pointer = $this->pointer - 1;;
    }
    
    /**
     * @return Integer
     */
    function top() {
        return $this->list[$this->pointer];
    }
    
    /**
     * @return Integer
     */
    function getMin() {
        return min($this->list);
    }
}

/**
 * Your MinStack object will be instantiated and called as such:
 * $obj = MinStack();
 * $obj->push($val);
 * $obj->pop();
 * $ret_3 = $obj->top();
 * $ret_4 = $obj->getMin();
 */
