<?php

/**
 * Autogenerated file for problem ReverseString
 */

namespace LeetCode\Problems\ReverseString;

class ReverseString
{
    /**
     * @param String[] $s
     * @return NULL
     */
    public function reverseString(&$s)
    {
        $s = implode('', $s);
        $s = strrev($s);
        $s = str_split($s);
        return $s;
    }
}
