<?php

/**
 * Autogenerated file for problem MaximumSubarray
 */

namespace LeetCode\Problems\MaximumSubarray;

class MaximumSubarray
{
    /**
     * @param Integer[] $nums
     * @return Integer
     */
    public function maxSubArray($nums)
    {
        if (empty($nums)) {
            return 0;
        } elseif (count($nums) <= 2) {
            return max($nums[0], $nums[1], $nums[0] + $nums[1]);
        }
        $max = $nums[0];
        $current = $nums[0];
        for($i = 1; $i < count($nums);$i++) {
            if ($current < 0) {
                $current = $nums[$i];
            } else {
                $current += $nums[$i];
            }
            $max = max($current, $max);
        }
        return $max;
    }
}
