<?php

/**
 * Autogenerated file for problem NimGame
 */

namespace LeetCode\Problems\NimGame;

class NimGame
{
    /**
     * @param int $n
     * @return bool
     */
    public function canWinNim($n)
    {
        $n = $n % 4;
        if ($n == 0) {
            return false;
        }
        return true;
    }
}
