<?php

/**
 * Autogenerated file for problem IntersectionMultipleArrays
 */

namespace LeetCode\Problems\IntersectionMultipleArrays;

class IntersectionMultipleArrays
{
    /**
     * @param Integer[][] $nums
     * @return Integer[]
     */
    function intersection($nums) {
        $result = array_unique($nums[0]);
        unset($nums[0]);
        foreach ($nums as $value) {
            $result = array_intersect($result, array_unique($value));
        }
        return $result;
    }
}
