<?php

/**
 * Autogenerated file for problem InvertBinaryTree
 */

namespace LeetCode\Problems\InvertBinaryTree;

use LeetCode\Problems\Helpers\TreeNode;

class InvertBinaryTree
{
    /**
     * @param TreeNode $root
     * @return TreeNode
     */
    public function invertTree($root)
    {
        if (!$root) {
            return null;
        }
        return $this->cloneTreeInvert($root);
    }

    public function cloneTreeInvert($root)
    {
        if (!$root) {
            return null;
        }
        $base = new TreeNode($root->val);
        if (isset($root->left)) {
            $base->right = $this->cloneTreeInvert($root->left);
        }
        if (isset($root->right)) {
            $base->left = $this->cloneTreeInvert($root->right);
        }
        return $base;
    }
}
