<?php

/**
 * Autogenerated file for problem RemoveAdjDuplStrII
 */

namespace LeetCode\Problems\RemoveAdjDuplStrII;

class RemoveAdjDuplStrII
{
    /**
     * @param String $s
     * @param Integer $k
     * @return String
     */
    function removeDuplicates($s, $k) {
        $len = strlen($s);
        $m_t = new \SplStack();
        for ($i=0; $i<$len; $i++) {
            $h_t = new \SplStack();
            $h_t->push($s[$i]);
            while (!$m_t->isEmpty() && $m_t->top() == $s[$i]) {
                $h_t->push($m_t->pop());
            }
            if ($h_t->count() != $k) {
                while (!$h_t->isEmpty()) {
                    $m_t->push($h_t->pop());
                }
            }
        }
        $str = '';
        while (!$m_t->isEmpty()) {
            $str .= $m_t->pop();
        }
        return strrev($str);
    }
}
