<?php

/**
 * Autogenerated file for problem FirstBadVersion
 */

namespace LeetCode\Problems\FirstBadVersion;

class FirstBadVersion
{

    /**
     * @param int $n
     * @return bool
     */
    function isBadVersion($n) {
       return $n === 4 ? 1 : 0;
    }

    /**
     * @param int $n
     * @return int
     */
    function firstBadVersion($n) {
        $start = 1;
        $end = $n;
        $bad = 0;
        while ($start <= $end) {
            $mid = (int)floor(($start + $end) / 2);
            if ($this->isBadVersion($mid)) {
                $bad = $mid;
                $end = $mid - 1;
            } else {
                $start = $mid + 1;
            }
        }
        return $bad;
    }
}
