<?php

/**
 * Autogenerated file for problem ImplementQueueStacks
 */

namespace LeetCode\Problems\ImplementQueueStacks;

class ImplementQueueStacks
{
    protected $queue;
    /**
     */
    public function __construct()
    {
        $this->queue = [];
    }

    /**
     * @param Integer $x
     * @return NULL
     */
    public function push($x)
    {
        $this->queue[] = $x;
    }

    /**
     * @return Integer
     */
    public function pop()
    {
        return array_shift($this->queue);
    }

    /**
     * @return Integer
     */
    public function peek()
    {
        return $this->queue[0];
    }

    /**
     * @return Boolean
     */
    public function empty()
    {
        return empty($this->queue);
    }
}
