<?php

/**
 * Autogenerated file for problem ImplementQueueStacks
 */

namespace LeetCode\Problems\ImplementQueueStacks;

class ImplementQueueStacks
{
    protected $queue;
    /**
     */
    function __construct() {
        $this->queue = [];
    }
    
    /**
     * @param Integer $x
     * @return NULL
     */
    function push($x) {
        $this->queue[] = $x;
    }
    
    /**
     * @return Integer
     */
    function pop() {
        return array_shift($this->queue);
    }
    
    /**
     * @return Integer
     */
    function peek() {
        return $this->queue[0];
    }
    
    /**
     * @return Boolean
     */
    function empty() {
        return empty($this->queue);
    }
}
