<?php

/**
 * Autogenerated file for problem VariableAfterPerformingOperations
 */

namespace LeetCode\Problems\VariableAfterPerformingOperations;

class VariableAfterPerformingOperations
{
    /**
     * @param String[] $operations
     * @return Integer
     */
    public function finalValueAfterOperations($operations)
    {
        return 1;
    }
}
