<?php

/**
 * Autogenerated file for problem VariableAfterPerformingOperations
 */

namespace LeetCode\Problems\VariableAfterPerformingOperations;

class VariableAfterPerformingOperations
{
    /**
     * @param String[] $operations
     * @return Integer
     */
    function finalValueAfterOperations($operations) {
        return 1;
    }
}
