<?php

/**
 * Autogenerated file for problem NumberStepsReduceNumberZero
 */

namespace LeetCode\Problems\NumberStepsReduceNumberZero;

class NumberStepsReduceNumberZero
{
    /**
     * @param Integer $num
     * @return Integer
     */
    function numberOfSteps($num) {
        $count = 0;
        if ($num % 2 == 1) {
            $num = $num - 1;
            $count++;
        }
        while ($num > 0) {
            if ($num % 2 == 0) {
                $num = $num / 2;
            } else {
                $num = $num - 1;
            }
            $count++;
        }
        return $count;
    }
}
