<?php

/**
 * Autogenerated file for problem ReplaceElemGreatElemRtSide
 */

namespace LeetCode\Problems\ReplaceElemGreatElemRtSide;

class ReplaceElemGreatElemRtSide
{
    /**
     * @param Integer[] $arr
     * @return Integer[]
     */
    public function replaceElements($arr)
    {
        $length = count($arr);
        if ($length === 1) {
            return [-1];
        }
        for ($i = 0; $i < $length; $i++) {
            $max = 0;
            for ($j = $i + 1; $j < $length; $j++) {
                $max = max($max, $arr[$j]);
            }
            $arr[$i] = $max;
        }
        $arr[$length - 1] = -1;
        return $arr;
    }

    /**
     * @param Integer[] $arr
     * @return Integer[]
     */
    public function replaceElementsOpt($arr)
    {
        $length = count($arr) - 1;
        $last = $arr[$length];
        $arr[$length] = -1;
        for ($i = $length - 1; $i >= 0; $i--) {
            $o = $last;
            $last = max($last, $arr[$i]);
            $arr[$i] = $o;
        }
        return $arr;
    }
}
