<?php

/**
 * Autogenerated file for problem DetectCapital
 */

namespace LeetCode\Problems\DetectCapital;

class DetectCapital
{
    /**
     * @param String $word
     * @return Boolean
     */
    function detectCapitalUse($word) {
        $length = strlen($word);
        $pattern = '';
        for($i=0; $i<$length; $i++) {
            $code = ord($word[$i]);
            if ($code >= 65 && $code <=90) {
                $pattern .= 1;
            } else if ($code >= 97 && $code <= 122) {
                $pattern .= 2;
            }
        }
        // check all 1
        if (substr_count($pattern, '1') === $length || substr_count($pattern, '2') === $length) {
            return TRUE;
        }
        if ($pattern[0] == 1) {
            $pattern = substr($pattern, 1);
            if (substr_count($pattern, '2') == ($length - 1)) {
                return TRUE;
            }
        }
        return FALSE;
    }
}

$dc = new DetectCapital();
$dc->detectCapitalUse('Lasa');