<?php

/**
 * Autogenerated file for problem FindDifference
 */

namespace LeetCode\Problems\FindDifference;

class FindDifference
{
    /**
     * @param String $s
     * @param String $t
     * @return String
     */
    public function findTheDifference($s, $t)
    {
        $a = str_split($t);
        for($i = 0; $i < strlen($s); $i++) {
            $key = array_search($s[$i], $a);
            unset($a[$key]);
        }
        return end($a);
    }
}
