<?php

/**
 * Autogenerated file for problem IntersectionTwoArrays
 */

namespace LeetCode\Problems\IntersectionTwoArrays;

class IntersectionTwoArrays
{
    /**
     * @param Integer[] $nums1
     * @param Integer[] $nums2
     * @return Integer[]
     */
    public function intersection($nums1, $nums2)
    {
        $a3 = array_intersect($nums1, $nums2);
        return array_unique($a3);
    }
}
