<?php

/**
 * Autogenerated file for problem PeekingIterator
 */

namespace LeetCode\Problems\PeekingIterator;

class PeekingIterator
{
    protected $arrIterator;

    /**
     * @param ArrayIterator $arr
     */
    public function __construct(\ArrayIterator $arr)
    {
        $this->arrIterator = $arr;
    }

    /**
     * @return Integer
     */
    public function next()
    {
        $current = $this->arrIterator->current();
        $this->arrIterator->next();
        return $current;
    }

    /**
     * @return Integer
     */
    public function peek()
    {
        $key = $this->arrIterator->key();
        return $this->arrIterator->offsetGet($key);
    }

    /**
     * @return Boolean
     */
    public function hasNext()
    {
        return $this->arrIterator->valid();
    }
}
