<?php

/**
 * Autogenerated file for problem DeleteNodeLinkedList
 */

namespace LeetCode\Problems\DeleteNodeLinkedList;

class DeleteNodeLinkedList
{
    /**
     * @param ListNode $node
     * @return
     */
    public function deleteNode($node)
    {
        $node->val = $node->next->val;
        $node->next = $node->next->next;
    }
}
