<?php

/**
 * Autogenerated file for problem SameTree
 */

namespace LeetCode\Problems\SameTree;

class SameTree
{
    /**
     * @param TreeNode $p
     * @param TreeNode $q
     * @return Boolean
     */
    function isSameTree($p, $q) {
        if (($p === null) && ($q === null)) return true;
        if (($p === null) || ($q === null) || ($p->val !== $q->val)) return false;
        return $this->isSameTree($p->left, $q->left) && $this->isSameTree($p->right, $q->right);
    }
}
