<?php

/**
 * Autogenerated file for problem ImplementStackusingQueues
 */

namespace LeetCode\Problems\ImplementStackusingQueues;

class ImplementStackusingQueues
{
    protected $stack;
    protected $count;

    /**
     */
    function __construct() {
        $this->stack = [];
        $this->count = -1;
    }
    
    /**
     * @param Integer $x
     * @return NULL
     */
    function push($x) {
        $this->count++;
        $this->stack[] = $x;
    }
    
    /**
     * @return Integer
     */
    function pop() {
        $this->count--;
        return array_pop($this->stack);
    }
    
    /**
     * @return Integer
     */
    function top() {
        return $this->stack[$this->count];
    }
    
    /**
     * @return Boolean
     */
    function empty() {
        return $this->count < 0;
    }
}
