<?php

/**
 * Autogenerated file for problem ImplementStackusingQueues
 */

namespace LeetCode\Problems\ImplementStackusingQueues;

class ImplementStackusingQueues
{
    protected $stack;
    protected $count;

    /**
     */
    public function __construct()
    {
        $this->stack = [];
        $this->count = -1;
    }

    /**
     * @param Integer $x
     * @return NULL
     */
    public function push($x)
    {
        $this->count++;
        $this->stack[] = $x;
    }

    /**
     * @return Integer
     */
    public function pop()
    {
        $this->count--;
        return array_pop($this->stack);
    }

    /**
     * @return Integer
     */
    public function top()
    {
        return $this->stack[$this->count];
    }

    /**
     * @return Boolean
     */
    public function empty()
    {
        return $this->count < 0;
    }
}
