<?php

/**
 * Autogenerated file for problem LargestElementinanArray
 */

namespace LeetCode\Problems\LargestElementinanArray;

class LargestElementinanArray
{
    /**
     * @param Integer[] $nums
     * @param Integer $k
     * @return Integer
     */
    function findKthLargest($nums, $k) {
        sort($nums);
        $c = count($nums);
        return $nums[$c-$k];
    }
}
