<?php

/**
 * Autogenerated file for problem KSmallestElementBST
 */

namespace LeetCode\Problems\KSmallestElementBST;

class KSmallestElementBST
{
    protected $result;
    protected $count;

    /**
     * @param TreeNode $root
     * @param Integer $k
     * @return Integer
     */
    public function kthSmallest($root, $k)
    {
        $this->count = $k;
        $this->parseTree($root);
        return $this->result;
    }

    public function parseTree($root = null)
    {
        if (is_null($root)) {
            return;
        }
        $this->parseTree($root->left);
        if (--$this->count == 0) {
            $this->result = $root->val;
            return;
        }
        $this->parseTree($root->right);
    }
}
