<?php

/**
 * Autogenerated file for problem ContainsDuplicateII
 */

namespace LeetCode\Problems\ContainsDuplicateII;

class ContainsDuplicateII
{
    /**
     * @param Integer[] $nums
     * @param Integer $k
     * @return Boolean
     */
    public function containsNearbyDuplicate($nums, $k)
    {
        $visited = [];
        foreach($nums as $i => $n) {
            if (isset($visited[$n])) {
                if (abs($i - $visited[$n]) <= $k) {
                    return true;
                }
            }
            $visited[$n] = $i;
        }
        return false;
    }
}
