<?php

/**
 * Autogenerated file for problem RunningSum1dArray
 */

namespace LeetCode\Problems\RunningSum1dArray;

class RunningSum1dArray
{
    /**
     * @param Integer[] $nums
     * @return Integer[]
     */
    function runningSum($nums) {
        $count = count($nums) - 1;
        $sum = array_sum($nums);
        $result = [];
        $negate = 0;
        for ($i=$count;$i>=0;$i--) {
            $result[$i] = $sum - $negate;
            $negate = ($negate + $nums[$i]);
        }
        return array_reverse($result);
    }
}
