<?php

/**
 * Autogenerated test case file for problem CountCompleteTreeNodeTest
 */

use LeetCode\Problems\CountCompleteTreeNode\CountCompleteTreeNode;
use LeetCode\Problems\Helpers\TreeNode;
use PHPUnit\Framework\TestCase;

final class CountCompleteTreeNodeTest extends TestCase
{
    public function testCountCompleteTreeNodeTestExample1()
    {
        $cctn = new CountCompleteTreeNode();
        $lnf = new TreeNode(11);
        $ln = new TreeNode(3, $lnf);
        $rn = new TreeNode(2);
        $mn = new TreeNode(1, $ln, $rn);
        $this->assertEquals(4, $cctn->countNodes($mn));
    }
}
