<?php

/**
 * Autogenerated test case file for problem DeleteColumnsMakeSortedTest
 */
namespace LeetCode\Tests;

use LeetCode\Problems\DeleteColumnsMakeSorted\DeleteColumnsMakeSorted;
use PHPUnit\Framework\TestCase;
final class DeleteColumnsMakeSortedTest extends TestCase
{
	public function testDeleteColumnsMakeSortedTestExample1()
	{
		$dcms = new DeleteColumnsMakeSorted();
		$this->assertEquals(1, $dcms->minDeletionSize(["cba", "daf", "ghi"]));
		$this->assertEquals(0, $dcms->minDeletionSize(["a", "b"]));
		$this->assertEquals(3, $dcms->minDeletionSize(["zyx","wvu","tsr"]));
		$this->assertEquals(2, $dcms->minDeletionSize(["rrjk","furt","guzm"]));
	}
}
