<?php

/**
 * Autogenerated test case file for problem DetectCapitalTest
 */

namespace LeetCode\Tests;

use LeetCode\Problems\DetectCapital\DetectCapital;
use PHPUnit\Framework\TestCase;

final class DetectCapitalTest extends TestCase
{
    public function testDetectCapitalTestExample1()
    {
        $dc = new DetectCapital();
        $this->assertEquals(true, $dc->detectCapitalUse('USA'));
        $this->assertEquals(true, $dc->detectCapitalUse('INDIA'));
        $this->assertEquals(true, $dc->detectCapitalUse('uasa'));
        $this->assertEquals(false, $dc->detectCapitalUse('FlaG'));
        $this->assertEquals(true, $dc->detectCapitalUse('Leetcode'));
    }
}
