<?php

/**
 * Autogenerated test case file for problem FizzBuzzTest
 */

namespace LeetCode\Tests;

use LeetCode\Problems\FizzBuzz\FizzBuzz;
use PHPUnit\Framework\TestCase;

final class FizzBuzzTest extends TestCase
{
    public function testFizzBuzzTestExample1()
    {
        $fb = new FizzBuzz();
        $this->assertEquals(["1", "2", "Fizz"], $fb->fizzBuzz(3));
    }
}
