<?php

/**
 * Autogenerated test case file for problem IsPowerOfThreeTest
 */
namespace LeetCode\Tests;
use LeetCode\Problems\IsPowerOfThree\IsPowerOfThree;
use PHPUnit\Framework\TestCase;
final class IsPowerOfThreeTest extends TestCase
{
	public function testIsPowerOfThreeTestExample1()
	{
		$ipot = new IsPowerOfThree();
		$this->assertEquals(true, $ipot->isPowerOfThree(27));
	}
}
