<?php

/**
 * Autogenerated test case file for problem KidsWithGreatestNumberCandiesTest
 */

use LeetCode\Problems\KidsWithGreatestNumberCandies\KidsWithGreatestNumberCandies;
use PHPUnit\Framework\TestCase;

final class KidsWithGreatestNumberCandiesTest extends TestCase
{
	public function testKidsWithGreatestNumberCandiesTestExample1()
	{
		$kwgnc = new KidsWithGreatestNumberCandies();
		$expected = $kwgnc->kidsWithCandies([2, 3, 5, 1, 3], 3);
		$this->assertEquals($expected, [true, true, true, false, true]);
	}
}
