<?php

namespace LeetCode\Tests;

/**
 * Autogenerated test case file for problem LongestCommonPrefix
 */

use LeetCode\Problems\LongestCommonPrefix\LongestCommonPrefix;
use PHPUnit\Framework\TestCase;

final class LongestCommonPrefixTest extends TestCase
{
	public function testLongestCommonPrefixExample1()
	{
        $lcp = new LongestCommonPrefix();
        $this->assertEquals("fl", $lcp->longestCommonPrefix(["flower", "flow", "flight"]));
        $this->assertEquals("", $lcp->longestCommonPrefix(["dog","racecar","car"]));
        $this->assertEquals("", $lcp->longestCommonPrefix(["rambo","gambo","jambo"]));
        $this->assertEquals("a", $lcp->longestCommonPrefix(["a"]));
        $this->assertEquals("", $lcp->longestCommonPrefix(["reflower", "flow", "flight"]));
        $this->assertEquals("", $lcp->longestCommonPrefix(["c", "acc", "ccc"]));
	}
}
