<?php

/**
 * Autogenerated test case file for problem MaximumIceCreamBarsTest
 */
namespace LeetCode\Tests;

use LeetCode\Problems\MaximumIceCreamBars\MaximumIceCreamBars;
use PHPUnit\Framework\TestCase;
final class MaximumIceCreamBarsTest extends TestCase
{
	public function testMaximumIceCreamBarsTestExample1()
	{
		$micb = new MaximumIceCreamBars();
		$this->assertEquals(4, $micb->maxIceCream([1,3,2,4,1], 7));
	}
}
