<?php

/**
 * Autogenerated test case file for problem MinimumNumberArrowsBalloonsTest
 */
namespace LeetCode\Tests;

use LeetCode\Problems\MinimumNumberArrowsBalloons\MinimumNumberArrowsBalloons;
use PHPUnit\Framework\TestCase;

final class MinimumNumberArrowsBalloonsTest extends TestCase
{
	public function testMinimumNumberArrowsBalloonsTestExample1()
	{
		$mnab = new MinimumNumberArrowsBalloons();
		$this->assertEquals(2, $mnab->findMinArrowShots([[10,16],[2,8],[1,6],[7,12]]));
		$this->assertEquals(2, $mnab->findMinArrowShots([[9,12],[1,10],[4,11],[8,12],[3,9],[6,9],[6,7]]));
	}
}
