<?php

/**
 * Autogenerated test case file for problem NimGameTest
 */

use LeetCode\Problems\NimGame\NimGame;
use PHPUnit\Framework\TestCase;
final class NimGameTest extends TestCase
{
	public function testNimGameTestExample1()
	{
		$nm = new NimGame();
		$this->assertEquals($nm->canWinNim(4), false);
	}
}
