<?php

/**
 * Autogenerated test case file for problem ReverseVowelsStringTest
 */

namespace LeetCode\Tests;

use LeetCode\Problems\ReverseVowelsString\ReverseVowelsString;
use PHPUnit\Framework\TestCase;

final class ReverseVowelsStringTest extends TestCase
{
    public function testReverseVowelsStringTestExample1()
    {
        $rvs = new ReverseVowelsString();
        $this->assertEquals('holle', $rvs->reverseVowels('hello'));
        $this->assertEquals('leetcode', $rvs->reverseVowels('leotcede'));
        $this->assertEquals('e', $rvs->reverseVowels('e'));
        $this->assertEquals('', $rvs->reverseVowels(''));
        $this->assertEquals('eeeee', $rvs->reverseVowels('eeeee'));
    }
}
