<?php

/**
 * Autogenerated test case file for problem ThirdMaximumNumberTest
 */

namespace LeetCode\Tests;

use LeetCode\Problems\ThirdMaximumNumber\ThirdMaximumNumber;
use PHPUnit\Framework\TestCase;

final class ThirdMaximumNumberTest extends TestCase
{
    public function testThirdMaximumNumberTestExample1()
    {
        $nums = [1, 2, 2, 5, 3, 5];
        $tmn = new ThirdMaximumNumber();
        $this->assertEquals(2, $tmn->thirdMax($nums));
    }
}
